### PR TITLE
Added config entry for giving advancements on join

### LINKED ISSUE #17: [1.12.2] (Suggestion) Option to disable automatic advancements?
(Minecraft version 1.12.2)

Regarding version **2.2.16** of Simply Jetpacks... (many thanks for all the work you put into this update, by the way!)

I'm getting a brief spam of unwanted achievements/advancements from this mod every time I create a new world now- the more integration modules enabled, the worse it is, as there's an achievement for every single module, as well as another that's just saying I've installed the mod.

In the interest of not confusing/overwhelming new players with anything superfluous, any chance these could be disabled via config option?

### PR DESCRIPTION
**Pull request by rlnt**
This should close #17

### CODE REVIEW

**Comment by tomheaton** [comment]
will check this tonight 👍

**Comment by rlnt** [comment]
I had an issue in my development environment where gradle was not able to resolve `The One Probe` and failed to build with the current mcp mappings.
I tinkered a little with the `build.gradle` and `gradle.properties` to get it to work but didn't push these changes as the main focus only lies on that feature. I think you should know best what to do with the versions on your mod.
Hope it helps.

**Comment by Tomson124** [comment]
@Th0mas-7 Took the liberty and looked at it and checked everything, looks fine :)

@DAmNRelentless Thanks a lot. Appreciate the work :)

**Comment by xJon** [comment]
Was this supposed to also affect this?
image
https://github.com/Tomson124/SimplyJetpacks2/issues/17#issuecomment-740978503

**Pull request merged**
